### ISSUE TITLE
Vulnerability detected on snyk for lodash dependency

### ISSUE THREAD

**Issue by cianfoley-nearform** [monken/node-pbac#4]
https://snyk.io/vuln/npm:lodash:20180130

Hey @monken, is there a major issue to Upgrade lodash to version 4.17.5 to address this?

I could branch and see if updating breaks test cases?

**Comment by monken** [comment]
Not at all. I'll get on it. We don't use any fancy lodash functions. We might have to adapt to the new naming conventions but that's all. I'll have a crack at it!

**Comment by monken** [comment]
I'm planning to drop support for NodeJS <= 0.12. Would that be ok for you?

**Comment by monken** [comment]
@asprouse thanks for your work on porting this over to lodash 4. I've cherry-picked your commit.

**Comment by cianfoley-nearform** [comment]
thanks very much @monken @asprouse

**Comment by cianfoley-nearform** [comment]
sorry to bother you guys... not sure if this is related but updated and noticed in StringLike
that something like 

/myapp/users/*
no longer matches
something like /myapp/users/test

is that correct?

**Comment by monken** [comment]
@cianfoley-nearform I added a test with your case and it passes. Could you provide the full policy?

**Comment by cianfoley-nearform** [comment]
We were using fn(b, a), it works if I switch to fn(a, b)

**Comment by cianfoley-nearform** [comment]
Hi @monken, will pbac be released with updated lodash soon?

the package i got via npm i is referring to older version of lodash...

**Comment by monken** [comment]
just released v0.3.0
