### ISSUE TITLE
Bool conditions require boolean values

### ISSUE THREAD

**Issue by jdiamond** [monken/node-pbac#5]
Hi, this project is awesome. Encountered a few issues while integrating it with our application.

This doesn't work:

```
{"Bool": {"foo:bar": "true"}}
```

This does:

```
{"Bool": {"foo:bar": true}}
```

The AWS docs show `"true"` (with quotes) instead of `true` (without quotes):

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_Boolean

Is that a mistake in the AWS docs? Your code specifically requires the values to be booleans:

```
  Bool(a, b) {
    if (!isBoolean(a) || !isBoolean(b)) return false;
    return a === b;
  },
```

I prefer not having quotes, but had them because that's what the docs showed. Just wanted to file an issue in case you wanted to match the AWS docs.

**Comment by monken** [comment]
Thanks for that catch! AWS policies are mostly string based so it's definitely a bug in my code. I should probably also review other non-string comparison operators.
